function ax = ApplyFigureFormat(fig)
%% ApplyFigureFormat - Apply paper-level axes formatting

    if nargin < 1 || isempty(fig)
        fig = gcf;
    end

    style = PaperStyle();
    set(fig, 'Color', style.figureColor, 'Renderer', 'painters');

    ax = findall(fig, 'Type', 'axes');
    if isempty(ax)
        ax = gca;
    end

    for i = 1:numel(ax)
        set(ax(i), ...
            'FontName', style.fontName, ...
            'FontSize', style.axesFontSize, ...
            'LineWidth', 1.3, ...
            'Box', 'on', ...
            'TickDir', 'in', ...
            'TickLength', [0.015 0.015], ...
            'Layer', 'top', ...
            'XColor', style.colors.black, ...
            'YColor', style.colors.black);
        grid(ax(i), 'off');
        set(ax(i), ...
            'GridAlpha', style.gridAlpha, ...
            'MinorGridAlpha', style.minorGridAlpha);
    end
end

